# This file was generated by GoReleaser. DO NOT EDIT.
cask "qilin" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "147b8cc0e7149917ba0fab7fa3beff7af10e30c44b65fe1a056c268154421486"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f696215b022cbda94703eebd872045081df06baea766565069b099f0c2132dc2"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68d4cc89cc1302ce732159b2aaf71ca58dee0ec1ae22f4a3631a633041941dfd"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "45ef8048e1c946d614ec61f8143e8f213bf7c6497b6e645fe87a7ecc3ba49013"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qilin"
  desc "Plug-and-play vector memory exposed over MCP/SSE."
  homepage "https://github.com/dev-creations/qilin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qilin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/qilin"]
    end
  end

  # No zap stanza required

end
