# This file was generated by GoReleaser. DO NOT EDIT.
cask "qilin" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "11702f1ed087ef54092a0fad8b6ddcc0cdc84be243d2a67ba11e49f2db389fef"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3e62f3a53c02995478985882395b0b9b6bad2decc9c88a57f7f3d8878099fa08"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c3bc3314a8fde39dfaefede177983593207a4cbccfb74aa9bc14c676adefb03"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3c1153777d758de7deb45c65005c82ab3d3efc88838ce1377b2f7711c9cc84d1"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qilin"
  desc "Plug-and-play vector memory exposed over MCP/SSE."
  homepage "https://github.com/dev-creations/qilin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qilin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/qilin"]
    end
  end

  # No zap stanza required

end
