# This file was generated by GoReleaser. DO NOT EDIT.
cask "qilin" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f85373a413d75a3ef0ac58b80a737dff266e9e0bc5c46461624c0d5fa4d674f9"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "880dbfc7fe289afd728e35a1cff4389486651b9fbb58f3762df99c687fd75a45"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96c3266c966210b1f03de0430dc1e0a74cfa0290d7c3d1fb0d66e8676b6644be"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b4024d056a7c4093e49cec621ccec8c0294421cfcb69e24076d87c09e5319700"
      url "https://github.com/dev-creations/qilin/releases/download/v#{version}/qilin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qilin"
  desc "Plug-and-play vector memory exposed over MCP/SSE."
  homepage "https://github.com/dev-creations/qilin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qilin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/qilin"]
    end
  end

  # No zap stanza required

end
